// Even Fibonacci numbers
// Show HTML problem content 
// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#include <iostream>

int main(){


	return 0;
};
